source $HOME/.config/nvim/layers/init.vim
source $HOME/.config/nvim/layers/readwrite.vim
source $HOME/.config/nvim/layers/textarea.vim
source $HOME/.config/nvim/layers/infoline.vim
source $HOME/.config/nvim/layers/statusline.vim
source $HOME/.config/nvim/layers/diff.vim
source $HOME/.config/nvim/layers/tui.vim
source $HOME/.config/nvim/layers/commands.vim
source $HOME/.config/nvim/layers/maps.vim
source $HOME/.config/nvim/layers/plugins.vim
