# Vagrantfile: Virtual desktop
# http://stackoverflow.com/questions/18878117/using-vagrant-to-run-virtual-machines-with-desktop-environment
#
# USAGE
#
#   Install Vagrant + VirtualBox, than run
#
#     $ vagrant up
#
#   To change the keyboard layout:
#
#     $ sudo dpkg-reconfigure keyboard-configuration
#
# OTHER BOXES
#
#   https://github.com/boxcutter

Vagrant.configure(2) do |config|
  config.vm.box = 'boxcutter/ubuntu1610-i386'

  config.vm.provider 'virtualbox' do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    vb.customize [
      'modifyvm', :id,
      '--memory', '2048',
      '--vram', '128',
    ]
  end

  # Install xfce and virtualbox additions
  config.vm.provision 'shell', inline: <<-SHELL
    # __ VIRTUALBOX RELATED _________________
    sudo apt-get update
    # sudo apt-get install -y xorg virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11

    # Permit anyone to start the GUI
    # sudo sed -i 's/allowed_users=.*$/allowed_users=anybody/' /etc/X11/Xwrapper.config

    # __ BASIC STUFF ________________________

    apt-get install -y zsh
    apt-get install -y git

    # __ DEVELOPEMENT _______________________

    apt-get install -y gcc make
    # apt-get install -y ctags

    apt-get install -y python python-pip python3 python3-pip

    apt-get install -y ruby ruby-dev
    gem install ripper-tags gem-ripper-tags
    gem install pry

    # __ SET UP USER ENVIRONMENT ____________

    git clone --progress --verbose https://github.com/bimlas/home ~/home
    cd ~/home
    source linux_user.sh
  SHELL
end
