#!/bin/bash
# git-stash-needs-message: Forcing myself to add description for stash

if [ -z "$*" ]; then
  echo You must provide a message
  exit 1
fi

git stash save --keep-index --include-untracked $*
