#!/bin/bash
# git-branch-status: List the status of merged/unmerged branches
#
# ==================== BimbaLaszlo (.github.io|gmail.com) ====================
echo 'MERGED (the current branch contains the tip of these branches)'

git branch -vv $@ --merged

echo -e 'NOT MERGED'

git branch -vv $@ --no-merged
