#!/bin/bash
# git-ctags: Regenerate CTags database
#
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-asciidoc,html,javascript,sql
mv "$dir/$$.tags" "$dir/tags"
