#!/bin/bash
# git-ctags: Regenerate CTags database
#
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

gitdir="`git rev-parse --git-dir`"
topdir="`git rev-parse --show-toplevel`"

cd $topdir

trap 'rm -f "$gitdir/$$.tags"' EXIT
git ls-files | grep -v '^test' | sed "s#.*#$topdir/&#" | \
  ctags -L - -f"$gitdir/$$.tags" --languages=-asciidoc,html,javascript,sql --fields=+i
mv "$gitdir/$$.tags" "$gitdir/tags"
