#!/bin/bash
# Rofi transform: Try to transform the selected number or text to different formats
#
# Usage:
#
#   Select the desired text by mouse in any app (terminal, PDF reader,
#   web browser, office apps, etc.) and press the shortcut.
#
# Dependencies:
#
#   - rofi
#   - xsel
#   - node

# Open Rofi
if [ ${?} -eq 0 ] && [ -z ${ROFI_RETV} ]; then
  rofi -show transform-number -modi transform-number:"${0}"

# List items
elif [ ${ROFI_RETV} -eq 0 ]; then
  SELECTED_TEXT=$(xsel -o)
  SELECTED_TEXT="'${SELECTED_TEXT}'"
  cat << _HEREDOC_
// Parsing ${SELECTED_TEXT} as ...
Date (milliseconds):            $(node -e "console.log(new Date(parseInt(${SELECTED_TEXT})).toISOString())" 2> /dev/null)
Date (seconds):                 $(node -e "console.log(new Date(parseInt(${SELECTED_TEXT}) * 1000).toISOString())" 2> /dev/null)
Hexadecimal -> decimal number:  $(node -e "console.log(BigInt(${SELECTED_TEXT}).toString())" 2> /dev/null)
Decimal -> hexadecimal number:  $(node -e "console.log('0x' + BigInt(${SELECTED_TEXT}).toString(16))" 2> /dev/null)
Base64 encode:                  $(node -e "console.log(btoa(${SELECTED_TEXT}))" 2> /dev/null)
Base64 decode:                  $(node -e "console.log(atob(${SELECTED_TEXT}))" 2> /dev/null)
_HEREDOC_
# TODO:
# 18 decimals:                    $(node -e "console.log(BigInt(${SELECTED_TEXT}) / 10n**18n))" 2> /dev/null)
# 6 decimals:                     $(node -e "console.log(BigInt(${SELECTED_TEXT}) / 10n**6n))" 2> /dev/null)

# Copy the value of selected item to the clipboard
else
  echo "${1}" | sed 's/^[^:]\+:\s\+//' | xsel --clipboard > /dev/null

fi
255
