#!/bin/bash
# Window list, project launcher, SSH list
# See https://github.com/bimlas/howto-distraction-free-desktop-workspace-for-developers for details

# Get script directory even if it's a symlink
SCRIPT=${BASH_SOURCE[0]}
while [ -L "${SCRIPT}" ]; do
  SCRIPT_DIR=$( cd -P "$( dirname "${SCRIPT}" )" >/dev/null 2>&1 && pwd )
  SCRIPT=$(readlink "${SCRIPT}")
  [[ $SCRIPT != /* ]] && SCRIPT="${SCRIPT_DIR}/${SCRIPT}"
done
export SCRIPT_DIR=$( cd -P "$( dirname "$SCRIPT" )" >/dev/null 2>&1 && pwd )

export WINDOW_MANAGER=${WINDOW_MANAGER:-awesome}
export PROJECTS_DIR=${PROJECTS_DIR:-${HOME}}

# rofi \
#   -show windowcd \
#   -modi windowcd,window,project:"${SCRIPT_DIR}/project",apps:"${SCRIPT_DIR}/apps",ssh \
#   -window-command "${SCRIPT_DIR}/../lib/join-windows.${WINDOW_MANAGER} {window}"

rofi \
  -show window \
  -modi window,combi \
  -combi-modi project:"${SCRIPT_DIR}/project",apps:"${SCRIPT_DIR}/apps",ssh \
  -window-command "${SCRIPT_DIR}/../lib/join-windows.${WINDOW_MANAGER} {window}"

