#!/bin/bash

case "$1" in
  rebase) [ -f composer.json ] && git composer-autoload >/dev/null 2>&1 &;;
esac

# Execute hook of current repository
if [ -f .git/hooks/`basename $0` ] && [ -x .git/hooks/`basename $0` ]; then
  .git/hooks/`basename $0`
fi
