#!/bin/sh
# Check for merge conflict markers in diff before commiting.

git diff --exit-code --color --cached -U0 -G'^[><|=]{7}[ $]'
if [ $? != 0 ]
then
    echo -e "\nWARNING: YOU HAVE MERGE CONFLICT MARKERS IN THE ABOVE HUNKS"
    echo "Pass -n|--no-verify to commit anyway."
    exit 1
fi

# Execute hook of current repository
if [ -f .git/hooks/`basename $0` ] && [ -x .git/hooks/`basename $0` ]; then
  .git/hooks/`basename $0`
fi
