#!/bin/sh

take()
{
  mkdir -p "$@" && cd "$@"
}

alias e='$EDITOR'
alias o='xdg-open'
alias g='git'
if typeset -f __git_complete > /dev/null; then
  __git_complete g __git_main
fi
alias k='kubectl'
alias pd='pushd'
alias ls='ls -Av --color --group-directories-first'
alias grep='grep --color'
alias du='du -b'
alias run='mosh run'
alias pm-hibernate='echo "NEVER USE IT!"'
alias hummingbot='pushd /media/bimlas/src/hummingbot/hummingbot; conda activate hummingbot; ./bin/hummingbot.py; conda deactivate; popd'

# Disable .vimrc in vim.tiny because of incompatible settings.
if [[ $(which vim.tiny 2> /dev/null) ]]; then
  alias vim.tiny='vim.tiny -u NONE'
fi

# When exiting from Midnight Commander, switch the shell to the current
# directory
if [[ $(which mc 2> /dev/null) ]]; then
  alias mc='. /usr/lib/mc/mc-wrapper.sh'
fi

if [[ $(which ssh 2> /dev/null) ]]; then
  ssh-tmux()
  {
    ssh -t $@ tmux new-session -As ssh
  }
fi

if [[ $(which mycli 2> /dev/null) ]]; then
  alias mycli='EDITOR="code --wait" PAGER="less -SiRFX" mycli'
fi

if [[ $(which nnn 2> /dev/null) ]]; then
  n()
  {
    NNN_TMPFILE=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd

    nnn -Hoe "$@"

    # cd on quit only on ^G
    if [ -f $NNN_TMPFILE ]; then
            . $NNN_TMPFILE
            rm -f $NNN_TMPFILE > /dev/null
    fi
  }
fi

if [[ -f ~/nh/install/games/nethack ]]; then
  alias nethack=~/nh/install/games/nethack
fi

# Do not close the image after gnuplot.
if [[ $(which gnuplot 2> /dev/null) ]]; then
  alias gnuplot='gnuplot -persist'
fi
