#!/bin/bash
# by http://github.com/jehiah
# modified by BimbaLaszlo

git for-each-ref --format="%(refname:short) %(upstream:short)" refs/heads | \
while read local remote
do
    git rev-list --left-right ${local}...${remote} -- 2>/dev/null >/tmp/git_upstream_status_delta || continue
    [ -z $local ] && local='\e[1;37mNONE\e[0m'
    [ -z $remote ] && remote='\e[1;37mNONE\e[0m'
    LEFT_AHEAD=$(grep -c '^<' /tmp/git_upstream_status_delta)
    RIGHT_AHEAD=$(grep -c '^>' /tmp/git_upstream_status_delta)
    LEFT=''
    RIGHT=''
    [ $LEFT_AHEAD  != 0 ] && LEFT=" ahead \e[0;32m$LEFT_AHEAD\e[0m"
    [ $RIGHT_AHEAD != 0 ] && RIGHT=" behind \e[0;31m$RIGHT_AHEAD\e[0m"
    echo -e "\e[0;32m$local\e[0m...\e[0;31m$remote\e[0m$LEFT$RIGHT"
done
