#!/bin/bash
# Update Ruby documentation database

# Do nothing if there is no Ruby files, because Rdoc wants to generate
# documentation for every file in this case.
(find -name '*.rb' | grep '.*' &> /dev/null) && rdoc --all --ri '**/*.rb'
