#!/bin/bash
#
# imgdevpath: The uuid of the partition containing the iso.
# isofile:    Path of the iso.
# isoname:    Name of the disc. (use isoinfo to find out)
#
# Do not forget to update-grub
cat << EOF
menuentry 'Install arch with evolution from /boot/iso/evolution.iso' {
        set imgdevpath='/dev/disk/by-uuid/1eb63246-09bc-4f67-974a-a706ba3b48a5'
        set isofile='/boot/iso/evolution.iso'
        set isoname='Evolution-201412-32bit'
        loopback loop \$isofile
        linux (loop)/arch/boot/i686/vmlinuz archisolabel=\$isoname img_dev=\$imgdevpath img_loop=\$isofile earlymodules=loop
        initrd (loop)/arch/boot/i686/archiso.img
}
EOF
