//                                                                    tag:html

:lang:   hu
:toc:    right
:icons:  font

= Weboldalak többnyelvűségének beállítása
BimbaLaszlo
2014.10.20

A Google
https://support.google.com/webmasters/answer/182192?hl=hu&ref_topic=2370587#1[Multiregionális és többnyelvű webhelyek^]
című leírása alapján készült.

== Multiregionális és többnyelvű webhelyek

A mi oldalunk _mutliregionális_, azaz külön oldalakon szerepelnek a
fordítások, nem pedig egy oldalon belül választhatóak a nyelvek (ezt
_többnyelvű_ weboldalnak hívják).

A metaadatok (pl. `lang`) nem befolyásolják a _Google_-t, mert azok figyelembe
vétele helyett az oldal tartalma, a látható adatok alapján határozza meg, hogy
a webhely mely országot célozza meg. Néhány dolog, amiket figyel:

* Az oldal írott szövegének nyelve;
* városnevek, telefonszámok, valutanemek;
* stb.

A _Google Webmestereszközök_-ben az "`országcélzás`" eszközzel lehet beállítani,
hogy az adott oldal mely országot célozza meg, viszont ezt csak "`általános`"
_url_ címekkel lehet használni, amelyek nem tartalmaznak országkódot (pl.
http://www.naturtrend.com/; http://de.naturtrend.com/;
http://www.naturtrend.com/de/), mivel az országkód egyértelműen meghatározza a
célközönséget (pl.: http://www.naturtrend.de/).

"... ugyanazt a tartalmat ugyanazoknak a felhasználóknak különböző URL-eken
biztosítja (például amennyiben az example.de/ és az example.com/de/ is német
nyelvű tartalmat jelenít meg a németországi felhasználók számára), akkor
érdemes kiválasztani egy előnyben részesített verziót, és ennek megfelelően
https://support.google.com/webmasters/answer/93633[átirányítást^] végrehajtani
(vagy a
https://support.google.com/webmasters/answer/answer.py?answer=139394[rel=canonical^]
linkelemet használni)."
-- Multiregionális és többnyelvű webhelyek / Ismétlődő tartalom és a nemzetközi webhelyek

== A hreflang használata nyelvi és regionális url-ekhez

A fordítások kapcsolatát legegyszerűbben az oldal fejlécében elhelyezett
hivatkozásokkal tudjuk jelezni, pl. a magyar oldal `<head>` részében
feltüntetjük a német és angol verziókat is:

[source,html]
---------------------------------------
<link rel="alternate" hreflang="hu" href="http://www.szizaltrend.hu/oldal.html" />
<link rel="alternate" hreflang="de" href="http://www.de.naturtrend.com/seite.html" />
<link rel="alternate" hreflang="en" href="http://www.bamboorattancane.co.uk/page.html" />
---------------------------------------

[NOTE]
=======================================
Az aktuális oldalnak is szerepelnie kell a felsorolásban.

A kétbetűs nyelvkódokat kell használni, mint pl.: `en` (lásd:
http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO 639-1^]), vagy pl. ha
ausztriai németeknek szánt weboldalt készítettünk, akkor a `de-au` jelölést
használjuk (kód második részét az
http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2[ISO 3166-1] táblázatban
találhatjuk).

Ha létezik egy olyan oldal, amely csak a nyelv meghatározásához használt
"`főoldalként`" szerepel, akkor azt is fel kell venni a listába
`hreflang="x-default"` értékkel.

=======================================
