#!/bin/bash

# Indicate the unfinished tasks

if ( git --no-pager diff --cached -U0 | grep '^+.*TODO' > /dev/null ); then
  line='WARNING: Commit introducing TODOs'
  if ! ( grep "$line" "$1" > /dev/null ); then
    sed -i.bak -e "/# Please enter the commit message for your changes./ s,^,$line\n\n," $1
  fi
fi

# Append issue number / bug tracking URL to commit.
#
# If the branch name contains the issue number, it will append it to the
# commit message. Example:
#
#   BRANCH NAME            LINE TO APPEND
#   feature/GH-123-emoji   GitHub: #123
#   WRIKE-123-add-payment  Wrike: https://www.wrike.com/open.htm?id=123
#   UNKNOWN-123            Issue: #123

branchName=`git rev-parse --abbrev-ref HEAD`

IFS=- read issueTracker issueNumber <<< $(echo $branchName | sed -nr 's,([a-z-]+/)?([A-Z]+-[0-9]+).*,\2,p')

if ! [[ -z $issueNumber ]]; then

  firstline=''
  lastline=''
  case "$issueTracker" in
    WRIKE)
      lastline="Wrike: https://www.wrike.com/open.htm?id=$issueNumber"
      ;;
    GITHUB)
      lastline="GitHub: #$issueNumber"
      ;;
    GITLAB)
      lastline="GitLab: #$issueNumber"
      ;;
    # JIRA
    AF)
      firstline="$issueTracker-$issueNumber "
      ;;
    MP)
      firstline="$issueTracker-$issueNumber "
      ;;
    *)
      lastline="Issue: #$issueNumber"
      ;;
  esac

  # If the commit message already contains the line (`--amend`), then do
  # not add it again.
  if ! ( grep "$lastline" "$1" > /dev/null ); then
    sed -i.bak -e "/# Please enter the commit message for your changes./ s,^,$lastline\n\n," "$1"
  fi
  if ! [ -z "$firstline" ] && ! ( grep "$firstline" "$1" > /dev/null ); then
    echo "$firstline" > "$1.bak"
    cat "$1" >> "$1.bak"
    mv "$1.bak" "$1"
  fi
fi

# Execute hook of current repository
if [ -f .git/hooks/`basename $0` ] && [ -x .git/hooks/`basename $0` ]; then
  .git/hooks/`basename $0`
fi
